version: '3'
services:
  app:
    hostname: app
    build:
      context: .
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
    volumes:
      - .:/home/app/mongodb-replicaset
      - /home/app/mongodb-replicaset/node_modules

  mongodb3:
    image: mongo:3.0.14
    command: mongod --replSet "rs0" --smallfiles --oplogSize 128

  mongodb2:
    image: mongo:3.0.14
    command: mongod --replSet "rs0" --smallfiles --oplogSize 128

  mongodb1:
    image: mongo:3.0.14
    command: mongod --replSet "rs0" --smallfiles --oplogSize 128

  mongodbConfigRs0:
    image: mongo:3.0.14
    volumes:
      - ./scripts/:/scripts
    command: bash -c "chmod +x /scripts/mongodb_rs0_config.sh && ./scripts/mongodb_rs0_config.sh"

  mongodb4:
    image: mongo:3.0.14
    command: mongod --replSet "rs1" --smallfiles --oplogSize 128

  mongodb5:
    image: mongo:3.0.14
    command: mongod --replSet "rs1" --smallfiles --oplogSize 128

  mongodb6:
    image: mongo:3.0.14
    command: mongod --replSet "rs1" --smallfiles --oplogSize 128

  mongodbConfigRs1:
    image: mongo:3.0.14
    volumes:
      - ./scripts/:/scripts
    command: bash -c "chmod +x /scripts/mongodb_rs1_config.sh && ./scripts/mongodb_rs1_config.sh"

  mongodbConfigServer:
    image: mongo:3.0.14
    command: mongod --configsvr --smallfiles

  mongodbRouter:
    image: mongo:3.0.14
    command: mongos --configdb mongodbConfigServer

  shardConfig:
    image: mongo:3.0.14
    command: bash -c "chmod +x /scripts/shard_config.sh && ./scripts/shard_config.sh"
    volumes:
      - ./scripts/:/scripts

